### ISSUE TITLE
Problemas visualización número de cuotas y monto de cada cuota en detalle de pago

### ISSUE THREAD

**Issue by juanherna123456789** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#10]
**Describe el bug**

Estimados,
Estaba probando el ambiente de integración y me percate que al usar las tarjetas de crédito y seleccionar 1 o N cuotas en webpay luego no aparecen reflejadas en el detalle de pago de mi comercio Ejemplo en el detalle de pago

Tipo de cuota:	Sin cuotas
Monto compra:	$14.268
Número de cuotas:	-
Monto de cada cuota:	-
 

**Comportamiento observado**
no reporta que es con cuotas, el numero de cuotas y el monto.

**Comportamiento esperado**
que reporte si es con cuotas, el numero de cuotas y el monto de la cuota en el detalle de pedido

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/62325399/99472544-9bd7b300-2927-11eb-8a88-b921996c19e9.png)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: Transbank Webpay Plus REST Versión 1.0.1
- Woocommerce: Versión 4.7.0
- PHP: Versión 7.3.23

**Contexto adicional**

Lo pregunto, ya que es lo recomendado como minimo en https://www.transbankdevelopers.cl/

quedo atento, gracias

**Comment by eveperalta** [comment]
Hola tengo el mismo problema no pasa los datos de las cuotas, alguna recomendación para esto? o algún tiempo de respuesta? necesito pasar a producción el viernes y sin esa información imposible avanzar 

sitio de pruebas
[stage.la-reserva.cl](url)


Software E-commerce: | woocommerce
Version E-commerce: | 4.7.1

Estado de PHP | OK
 Versión: | 7.2.33
Última versión del plugin: | 1.0.1

También me di cuenta que al entrar a la configuración del plugin genera un bug en la pantalla cambia el fondo de color del admin y la tipografia

Log:
[2020-12-01 22:17:47] [INFO ] INFO: initTransaction - amount: 70990, sessionId: 5fc6c10b57226, buyOrder: 2023, txDate: 01-12-2020, txTime: 22:17:47
[2020-12-01 22:17:47] [INFO ] INFO: createTransaction - initResult: {"token":"01ab02686052197bc6b451fc852f31918857f3864e22d1649ff6ed90dbb9895b","url":"https:\/\/webpay3gint.transbank.cl\/webpayserver\/initTransaction"}
[2020-12-01 22:18:49] [INFO ] INFO: getTransactionResult - tokenWs: 01ab02686052197bc6b451fc852f31918857f3864e22d1649ff6ed90dbb9895b

**Comment by juanherna123456789** [comment]
Realiza la misma prueba en producción con una tarjeta de crédito Real

**Comment by gonzunigad** [comment]
Hola! ¿esto les sigue ocurriendo? Voy a revisar en integración.

**Comment by gonzunigad** [comment]
Este PR resuelve el problema. En el próximo release (hoy o mañana) quedará resuelto. :)

**Comment by eveperalta** [comment]
> Realiza la misma prueba en producción con una tarjeta de crédito Real

pasa ok al back admin de woocommerce, pero tengo un desarrollo a medida que envia los datos de transbank anexos al mail, y me pasa datos incorrectos (OJO: aun estoy en la version soap y antes funcionaba ok)

![WhatsApp Image 2020-12-14 at 10 17 36 AM](https://user-images.githubusercontent.com/20928308/102090203-f0bdfa80-3dfb-11eb-8850-25835776bb94.jpeg)
