### ISSUE TITLE
Error al activar plugin

### ISSUE THREAD

**Issue by ricardo-mrgd** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#105]
Estimados,

Tengo el siguiente error al activar el plugin de transbank en mis sitio web WP V6.0.2, PHP V7.4.
Tengo la última versión del plugin 1.5.5.

El plugin no ha podido activarse porque ha provocado un error fatal.
Fatal error: Uncaught Error: Call to undefined method Logger::configure() in /home/munsaclvps/public_html/wp-content/plugins/transbank-webpay-plus-rest/src/Helpers/LogHandler.php:66 Stack trace: #0 /home/munsaclvps/public_html/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php(126): Transbank\WooCommerce\WebpayRest\Helpers\LogHandler->__construct() #1 /home/munsaclvps/public_html/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php(415): WC_Gateway_Transbank_Webpay_Plus_REST->__construct() #2 /home/munsaclvps/public_html/wp-includes/class-wp-hook.php(307): transbank_webpay_rest_on_webpay_rest_plugin_activation('') #3 /home/munsaclvps/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #4 /home/munsaclvps/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #5 /home/munsaclvps/public_html/wp-admin/plugins.php(194): do_action('activate_transb...') #6 {main} thrown in /home/munsaclvps/public_html/wp-content/plugins/transbank-webpay-plus-rest/src/Helpers/LogHandler.php on line 66

Quedo a la espera, esto me perjudica mucho...

**Comment by aperalta-todoacero** [comment]
Estimado.

Lograste solucionar el problema? me pasa lo mismo..

**Comment by Victorsitou** [comment]
Hola Ricardo.

¿Pudiste arreglar el problema? A mí me pasa lo mismo

**Comment by mvarlic** [comment]
Se corrije el problema cambiando la librería de logs a 'Monolog', gracias por reportarlo
