### ISSUE TITLE
Oneclick no funciona con HyperDB ( cluster de base de datos M/S)

### ISSUE THREAD

**Issue by infra-biboo** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#106]
Hola, actualmente uso HyperDB (el plugin oficial de wordpress para balancear las base de datos). Las transacciones con webpay plus funcionan sin ningún problema. Pero las de Oneclick no logran crear la orden, por lo que no es posible utilizarlo. 

Los errores que me arrojan son los siguientes.

WordPress database error Incorrect integer value: '' for column `name_database`.`wp_transbank_inscriptions`.`pay_after_inscription` at row 1 for query INSERT INTO `wp_transbank_inscriptions` (`token`, `username`, `order_id`, `user_id`, `pay_after_inscription`, `email`, `from`, `status`, `environment`, `commerce_code`) VALUES ('1111111111111111', 'WP:1:111111111', '109', 1, '', 'hola@email.com', 'checkout', 'initialized', 'LIVE', '11111111111') made by Transbank\WooCommerce\WebpayRest\Models\Inscription::create

`PHP Notice:  Undefined variable: wpdb in /var/www/sitio.com/html/wp-content/plugins/transbank-webpay-plus-rest/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php on line 473`

Revise el código y vi que tienen soporte para multisitio en la función que crea la orden, sería genial pudieran darle soporte a HyperDB para tiendas que requieren una  mayor escabilidad.

Espero puedan ayudarme.
Muchas gracias.

PD: he reemplazado algunos valores ya que entregaba el código de comercio y otros datos sensibles.

**Comment by infra-biboo** [comment]
En el archivo: WC_Gateway_Transbank_Oneclick_Mall_REST.php he cambiado este valor 'pay_after_inscription'  de false a true y ha funcionado, lo que revise es que es un cambio nuevo y no se si afectará el comportamiento del plugin o su seguridad. 

Agradezco sus comentarios.

**Comment by mastudillot** [comment]
Esto ya no debería ocurrir en la última versión, se ha cambiado el flujo de la clase de Oneclick.
