### ISSUE TITLE
Error: Call to undefined method GuzzleHttp\Utils::chooseHandler()

### ISSUE THREAD

**Issue by sebagutp** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#107]
Soy principiante, feliz si me ayudan!

Al instalar ambos plugin (WooCommerce + Transbank Webpay REST) y seguir las instrucciones, al momento de realizar la primera prueba del pago, Al poner "Realizar pago", en la pantalla del checkout, arroja ese error.

Call to undefined method GuzzleHttp\Utils::chooseHandler() 

La idea es que post esta acción, me re-dirija a la página de webpay plus.

![image](https://user-images.githubusercontent.com/118416589/202349289-42fa06fc-f045-42a8-b6e2-9b055d02e387.png)

Versiones 
- Transbank Webpay REST: [1.5.5]
- Woocommerce: [7.1.0]
- PHP: [8.0.25]

**Comment by Matiasnickolas** [comment]
Hola! ¿Que versión de guzzle estás ocupando? ¿Puedes probar con [esta](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases/download/1.6.1/transbank-webpay-plus-rest-guzzle7.zip) versión del plugin?

**Comment by otrab** [comment]
se cierra por no tener respuesta
