### ISSUE TITLE
Error: Call to undefined method Monolog\Logger::addInfo() 

### ISSUE THREAD

**Issue by luisalbertoc** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#109]
**Describe el bug**

Al momento de realizar el Checkout y finalizar la compra, aparece este error:
Call to undefined method Monolog\Logger::addInfo() 

Cambié todas las versiones de php y el error seguía, se solucionó cambiando a la versión anterior, lanzada en Septiembre 2022.

**Capturas de pantalla**

<img width="539" alt="Screen Shot 2022-12-24 at 15 13 38" src="https://user-images.githubusercontent.com/10420418/209447423-f361a9ba-afc1-4f0e-ad8d-eb7603c02446.png">

**Versiones
- Plugin: 1.6.0

Por favor, eviten hacer estas actualizaciones el día antes de Navidad

**Comment by luislavandero** [comment]
hola que tal luis , disculpa que te moleste estoy igual con mi sitio web.. hemos cambiado a todas las versiones php. 
tengo woocommer la ultima version y wordpress la ultima version. en php hemos cambiado todo y ninguna arranca para finalizar la venta me sale lo mismo que a ti. me podrias ayudar por favor hlep me !!!!!! - +56987690573 o si me puedes dar tu numero gracias

**Comment by otrab** [comment]
Hola Luis

Lamentamos lo ocurrido
Estamos resolviendo el error. De momento por favor usar la versión [1.5.5](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases)



Saludos!

**Comment by luislavandero** [comment]
Me puedes enviar
Plugin de esta versión para poder ejecutar

Gracias

Enviado desde Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Sebastian Saez ***@***.***>
Enviado: Monday, December 26, 2022 10:50:27 AM
Para: TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest ***@***.***>
Cc: luislavandero ***@***.***>; Comment ***@***.***>
Asunto: Re: [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest] Error: Call to undefined method Monolog\Logger::addInfo() (Issue #109)


Hola Luis

Lamentamos lo ocurrido
Estamos resolviendo el error. De momento por favor usar la versión 1.5.5<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTransbankDevelopers%2Ftransbank-plugin-woocommerce-webpay-rest%2Freleases&data=05%7C01%7C%7Cc21eb40ece9e400bcdc608dae74825b5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638076594307834489%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2F6a6w6joxODWl3eWSi4ui4xQJkwxHzjVIguU8uZQXTo%3D&reserved=0>

Saludos!

**Comment by otrab** [comment]
Luis en este link puedes revisar todas las versiones
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases
