### ISSUE TITLE
Es necesario agregar un warning que advierta que la moneda no está configurada como CLP

### ISSUE THREAD

**Issue by topotech** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#11]
**Descripción**

El método de pago no se puede activar si la moneda no está configurada como peso chileno, lo que es totalmente lógico. Aún así, woocommerce no genera ningún aviso sobre esto, así que si uno instala Transbank Webpay Plus REST inmediatamente sobre una instalación fresca antes de configurar la moneda, el programa automáticamente desactivará el nuevo medio de pago sin explicar por qué. 

**Para reproducir**

1. Instalar Woocommerce sobre instalación limpia.
2. Instalar Transbank Webpay Plus REST.
3. Hacer click "Configuración" del plug-in.
4. Activar el medio de pago y presionar "Guardar los cambios".

**Comportamiento observado**

Nada cambia, sin importar si lo que se haga, el medio de pago se desactiva automáticamente y sin aviso.

**Comportamiento esperado**

El comportamiento esperado por mí era que la activación funcionara, pero entendiendo que ello fue ilógico de mi parte, sería esperable que el plugin, de alguna manera, advirtiera que no puede ser activado si la  moneda está en dólares.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: Transbank Webpay Plus REST 1.0.1
- Woocommerce: 5.5.3 y 5.5.2
- PHP: 7.3.24

**Comment by gonzunigad** [comment]
Muchas gracias por reportar este issue. 
Este PR soluciona eso: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/pull/15
