### ISSUE TITLE
WORDPRESS 6.1 WEBPAY Error: Call to undefined method Monolog\Logger::addInfo() 

### ISSUE THREAD

**Issue by luislavandero** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#110]
**Describe el bug**

HEMOS ACTUALIZADO PLUGIN WEBPAY .
PERO AL MOMENTO DE PAGAR NOS ARROJA ESTE MENSAJE
Error: Call to undefined method Monolog\Logger::addInfo()

ESTUVE LEYENDO, HEMOS MODIFICADO EL PHP PARA QUE SEA COMPATIBLE CON LA NUEVA ACTUALIZACION DE TRANSBANK PERO NADA SIGUE SALIENDO EL MISMO MENSAJE, JUSTO AHORA DE NAVIDAD NO PUDIMOS VENDER. 

LLAME A SOPORTE Y NO SABEN COMO SOLUCIONAR, PIDEN QUE HAGAN TODO DE NUEVO PARA QUE NOS PUEDAN DAR UNA NUEVA API/KEY. NO TIENE SENTIDO. HABLE CON SUPERVISOR SE ADJUNTATON IMAGENES Y NOS ENTREGO OTRA API/KEY MISMO PROBLEMA , MISMO MENSAJE.

TENEMOS WORDPRESS 6.1 ULTIMA VERSION, NO PODEMOS DEGRADAR LA VERSION DE WORDPRESS POR QUE ES MUY RIGIDO.

SI ALGUIEN SABE COMO PODER SOLUCIONAR SE AGRADECE LA INFORMACION.

+56987690573 . ESTOY DISPUESTO A PAGAR PARA QUE NOS PUEDAN AYUDAR.

GRACIAS.

**Comment by mvarlic** [comment]
Se corrige en la version 1.6.1
