### ISSUE TITLE
Logs deberian ir en wp-content/uploads?

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#118]
Estimados,

Vimos que recientemente se cambió la ubicación de los logs dentro del plugin.
Creemos que lo correcto es que este archivo esté en wp-content/uploads de modo que modificaciones al plugin, actualizaciones no borren este registro de logs.

**Comment by TCattd** [comment]
@svenms concuerdo contigo. Me topé con este problema recientemente.

Envié un PR con el arreglo. Veremos si lo aceptan o no.

Esteban

**Comment by mastudillot** [comment]
Esto estará agregado en la siguiente versión del plugin, gracias por los comentarios.
