### ISSUE TITLE
Transbank Woocommerce Webpay Plugin Error.  Will not follow more than 5 redirects

### ISSUE THREAD

**Issue by Dca93** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#119]
Will not follow more than 5 redirects. This error appears when I want to check the plugin connection. I have tried

1.- Deactivate, delete and reinstall.
2.- delete plugin manually from file manager
3.- uninstall wordpress completely and try
4.- import backup
5.- deactivate all plugins except woocomerce and transbank.

Nothing I tried worked. I manage another wordpress with the same plugin and it works perfect.

Does anyone have any idea what else I can try?

**Comment by juliohv-chile** [comment]
Hi there, i think your are in a wrong place, try: https://transbank.continuumhq.dev/slack_community is a slack comunity but with oficial support.
