### ISSUE TITLE
Warning en WSSecuritySoapClient

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#12]
Hola!

En debug.log en un pedido en particular apareció:

[25-Nov-2020 03:49:12 UTC] PHP Warning:  DOMDocument::loadXML(): Empty string supplied as input in /home/chilevapo.cl/public_html/wp-content/plugins/transbank/vendor/transbank/transbank-sdk/lib/webpay/soap/WSSecuritySoapClient.php on line 57

Sólo quería saber si esto puede ser normal.

Saludos!

Ultima versión del plugin 
Woocommece 4.6.1
Wordpress 5.5.1
Php 7.4

**Comment by gonzunigad** [comment]
Hola! Este plugin usa la versión REST del API de transbank. Quizás eso te pasó en el plugin SOAP :)

**Comment by svenms** [comment]
Estoy usando la  2.7.8.
Igual fue algo que apareció alguna veces y me parece que no ha vuelto.

**Comment by gonzunigad** [comment]
Este repositorio es del plugin REST que va en la versión 1.0.1 recién. En este no puede volver a pasar porque ya no se ocupan esas librerías: `DOMDocument::loadXML()` :)
