### ISSUE TITLE
High Performance Order Storage (HPOS)

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#121]
Pronto, en Agosto 2023, High Performance Order Storage (HPOS) estará habilitado por defecto en Woocommerce.
Por el momento la versión actual del plugin no indica que es compatible con HPOS. Si ya lo es, sería ideal declararlo: https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility

Saludos!

**Comment by svenms** [comment]
Alguien sabe si el plugin es compatible con HPOS y tiene todas las consultas a la DB con CRUD ?

**Comment by OndaDigital** [comment]
Todavía no es compatible, solo faltan 8 días y ya he enviado un correo por todos los canales posibles desde hace meses y ninguno con respuesta. 
Qué gran negligencia por parte del equipo de Transbank. Mercadopago y Flow ya son compatible con HPOS, asi que les recomiendo que desactiven Transbank y comiencen a usar Mercadopago o Flow para recibir sus pagos y de esta forma aumentar el rendimiento de nuestras tiendas.

**Comment by FongWan** [comment]
Fue fácil el proceso de agregar soporte a HPOS, funcionando perfectamente en los sitios que manejo. Espero que los mantenedores de este repositorio puedan revisar y aceptar mi PR pronto.

**Comment by FongWan** [comment]
Fue fácil el proceso de agregar soporte a HPOS, funcionando perfectamente en los sitios que manejo. Espero que los mantenedores de este repositorio puedan revisar y aceptar mi PR pronto.

CC: @isabellaahc @mvarlic @Matiasnickolas

**Comment by lp-82** [comment]
hay alguna novedad sobre la compatibilidad con HPOS?

**Comment by FongWan** [comment]
> hay alguna novedad sobre la compatibilidad con HPOS?

Ya he entregado el PR hace un mes, pero aún no hay mantenedores que quieren echarle un ojo. Espero que lo revisen pronto.

@mastudillot @Matiasnickolas @mvarlic

**Comment by mastudillot** [comment]
Será agregado en la siguiente versión, gracias por la colaboración
