### ISSUE TITLE
Acceso a transacciones shop manager

### ISSUE THREAD

**Issue by Bundeskanzlerfont** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#129]
Hola, es posible que en futuras versiones pueda existir una casilla para darle acceso al shop manager para que pueda acceder a la tab transacctions. creo que es necesario para poder revisar el historico de pagos.

**Comment by mastudillot** [comment]
Por hora no se tiene considerado la opción de habilitar el acceso externo a la información de las transacciones.
