### ISSUE TITLE
Auto-actualización del plugin. Repo oficial WordPress.org o desde GitHub directo.

### ISSUE THREAD

**Issue by TCattd** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#13]
Lo reportado acá: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/issues/49

¿Será posible con la versión REST del plugin?.
Auto-actualizarlo desde el repositorio oficial de WordPress o, por último, con alguna librería incluida en el plugins para recibir actualizaciones desde los releases de este mismo repositorio en GitHub.

Publico acá, ya que esto (auto-actualizaciones) fue [descartado](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay/issues/49#issuecomment-737992841) para el plugin ahora legacy por lo que veo.

Por favor.
Espero esto continúe estando en consideración.

**Comment by gonzunigad** [comment]
Estamos en el proceso de subirlo. Te contamos como nos va!

**Comment by gonzunigad** [comment]
Traigo excelente noticias: https://wordpress.org/plugins/transbank-webpay-plus-rest/

![image (6)](https://user-images.githubusercontent.com/1103494/102550813-3cdb9a00-409d-11eb-9057-f6f7f7aa1398.png)

**Comment by TCattd** [comment]
De parte de incontables integradores, y mía por su puesto: muchas muchas gracias :)

**Comment by gonzunigad** [comment]
🎉
