### ISSUE TITLE
Permitir modificación de descripción de pasarela en plugin para WooCommerce

### ISSUE THREAD

**Issue by matiasweb** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#133]
Actualmente, en el plugin para WooCommerce de Transbank WebPay Plus, no es posible modificar el texto de la descripción de la pasarela de pago directamente desde la pestaña de configuración del plugin. Esto puede ser un inconveniente para los clientes que desean personalizar el mensaje y adaptarlo mejor a su negocio.

![descripcion_webpayplus](https://user-images.githubusercontent.com/33424858/233118306-425e333f-c51f-4d05-a4fb-88fe4b0a938c.png)

Por esta razón, propongo que en una futura actualización del plugin se agregue la funcionalidad de poder modificar el campo de descripción de la pasarela de pago directamente en la pestaña de configuración de WebPay Plus. Esto permitirá a los clientes poner el mensaje que ellos quieran y evitar el por defecto "Permite el pago de productos y/o servicios, con tarjetas de crédito, débito y prepago a través de Webpay Plus".

Tuve que editar la línea 123 del archivo "webpay-rest.php" para poder modificar el texto de la descripción, lo cual no es una solución ideal y puede ser una tarea difícil para usuarios no técnicos.

#134

**Comment by matiasweb** [comment]
#134

**Comment by FongWan** [comment]
No es necesario editar el archivo `webpay-rest.php`, se puede editar agregando las siguientes líneas en `functions.php`:

~~~php
add_filter('woocommerce_gateway_description', function ($description, $gateway_id) {
	if ('transbank_webpay_plus_rest' == $gateway_id) return 'Pagas con tu tarjeta de crédito, débito o prepago.';
	return $description;
}, 25, 2);
~~~

**Comment by mastudillot** [comment]
Hola @matiasweb, vamos a agregar esta funcionalidad en la siguiente liberación del plugin.
