### ISSUE TITLE
PHP Deprecated / PHP Warning

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#160]
Estimados,

En el Debug hemos podido ver el siguiente mensaje:
```

PHP Deprecated:  Required parameter $token follows optional parameter $result in /home/public_html/wp-content/plugins/transbank-webpay-plus-rest/src/Controllers/ResponseController.php on line 230
PHP Warning:  Undefined variable $token_ws in /home/public_html/wp-content/plugins/transbank-webpay-plus-rest/src/Controllers/ResponseController.php on line 220
```
Correspondiendo a un pago que no se aprobó finalmente.

Php: 8.1
Woocommerce ultima version
Wordpress ultima version

**Comment by mastudillot** [comment]
Hola @svenms gracias por el reporte, vamos a revisarlo para que en la siguiente versión se encuentre solucionado.

**Comment by mastudillot** [comment]
Hola @svenms esto queso solucionado en la versión 1.7.0 del plugin
