### ISSUE TITLE
Pagos exitosos no reflejados en la cuenta

### ISSUE THREAD

**Issue by isasaurio** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#161]
Usando Woocomerce y el plugin de Transbank Web Pay plus, se realizan ventas y llega el mensaje de "!Transacción Aprobada!" pero no se registra el pago en la cuenta asociada.

![image](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/10709329/f59078a5-cd85-47a5-af15-7fab252cae65)

- Plugin: [Versión 1.6.7]
- Woocommerce: [Versión 7.5.0]
- PHP: [7.1.33]

**Comment by mastudillot** [comment]
Los pagos aprobados son depositados de forma posterior a la fecha de la transacción, esto pueden ser revisados desde tu portal de Transbank, en la sección de abonos.
