### ISSUE TITLE
HPOS todavía no es compatible con Transbank 

### ISSUE THREAD

**Issue by OndaDigital** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#167]
Es realmente desconcertante que Transbank, a pesar de su relevancia en el mercado chileno, aún no haya anunciado su compatibilidad con HPOS. En una era de comercio electrónico eficiente, esta tardanza pone en desventaja a los comerciantes dependientes de sus servicios y muestra un desinterés en sus necesidades.

Saludos.

**Comment by mastudillot** [comment]
Será agregado en la siguiente versión del plugin

**Comment by ShipShape-Development** [comment]
> Será agregado en la siguiente versión del plugin

Podrían especificar cuantos meses faltan para la próxima versión del plugin? Ya que a 7 meses del OP no hay ninguna solución contreta y parece que la única opción es pasarse a pasarelas de pago más actuales y en sincronía con las necesidade de sus clientes.

Saludos

**Comment by melvisnap** [comment]
Hola, tendrán alguna novedad sobre esto?
