### ISSUE TITLE
Compatibilidad con Bloques

### ISSUE THREAD

**Issue by dhenriquez** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#168]
**Compatibilidad con Bloques**

Al momeno de activar la opción de bloques en la página de checkout nos mostró el mensaje que adjunto.

**Versiones (por favor agrega aquí la siguiente información):**
- Wordpress: 6.2.2
- Plugin: 1.6.8
- Woocommerce: 7.8.2
-WooCommerce Blocks 10.6.0
- PHP: 7.4.33

<img width="285" alt="Captura de Pantalla 2023-07-13 a la(s) 11 57 34" src="https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/1086940/c1a4e731-baff-4fc2-8dba-b73413a81d1a">

Aquí se puede encontrar la documenación para trabajar en la actualización:

https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md

**Comment by igcabrera** [comment]
ninguna respuesta de esto aun?

**Comment by mastudillot** [comment]
En la siguiente versión estará agregada la compabilidad con bloques, esperamos tenerla a principios de febrero.
