### ISSUE TITLE
Undefined variable $webpayPlusCommerceCode

### ISSUE THREAD

**Issue by FongWan** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#169]
Cuando se instala por primera vez el plugins en Wordpress y sin haber definido el código de comercio, al navegar hacia la sección de gestión de "Webpay Oneclick", aparece el siguiente mensaje en los registros de errores:

~~~log
PHP Warning:  Undefined variable $webpayPlusCommerceCode in /.../wp-content/plugins/transbank-webpay-plus-rest/views/admin/components/info-validacion-webpay-oneclick-box.php on line 6
~~~

## Pasos para reproducir el error:
1. Instalar el plugins en un Wordpress nuevo.
2. Navegar hacia "WooCommerce" > "Ajustes" > "Pagos" > Gestionar "Transbank Webpay Plus" > "Webpay Oneclick".

## Comportamiento esperado
Sin mensaje en los registros de errores.

**Comment by isabellaahc** [comment]
Hola @FongWan, muchas gracias por tu reporte. 
Vamos a revisar el error y te comentaremos cuando esté resuelto 👌

**Comment by mastudillot** [comment]
Esta corrección será incluida en la siguiente versión, muchas gracias
