### ISSUE TITLE
Multisitio

### ISSUE THREAD

**Issue by Giskrac** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#17]
Estimados, existe la posibilidad de agregar el soporte para multisitios?

**Comment by gonzunigad** [comment]
Hola @Giskrac . Este PR me aprece que soluciona este issue, ya que agrega compatibilidad con Wordpress MU. 
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/pull/9

En el próximo release estará disponible. Probablemente salga hoy.
