### ISSUE TITLE
Como usar webhooks?

### ISSUE THREAD

**Issue by lgaticaq** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#172]
Hola estoy tratando de agregar un webhook para que envié un post a un sitio externo, cuando se haga un pago exitoso con webpay plus. Revisando las release veo que crearon el hook `transbank_webpay_plus_transaction_approved`. Intente usar ese valor como "Evento de la acción", pero woocommerce no lo permite. Luego use el valor `woocommerce_transbank_webpay_plus_transaction_approved`, pero no funciona. Me pueden guiar como crear de forma correcta un webhook para esa finalidad, por favor. Estoy usando el ambiente de pruebas para hacer pruebas de integración.

![image](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/661958/bd2b9196-ae0f-487b-9f80-cf087b0f12e5)

**Comment by mastudillot** [comment]
Hola @lgaticaq

Revisamos la implementación de los webhooks y no estaba funcionando como se esperaba. 

Ene este PR se implementa la corrección, en la siguiente versión ya va a estar solucionado.
