### ISSUE TITLE
Error al comprar en la página web 

### ISSUE THREAD

**Issue by shapinerox** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#173]
al intentar comprar en la pág web me sale este error:
![image](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/148922816/60034db4-717a-494b-87fe-c05459ef1444)
y me sale desde que añadí el plugin de webpay plus... alguna idea de como solucionarlo? tengo bien configurado el plugin y no sé por qué esta dando errores.

**Comment by victormendoza96** [comment]
Hola @shapinerox, para problemas con tu integración te invita al canal de slack donde te podemos brindar soporte, deja tus preguntas en el canal general y el que este dando soporte ese día te puede ayudar😄 

https://join.slack.com/t/transbankdevelopers/shared_invite/zt-25x26zec1-noZUlMbQRn6pP7oXLRG3mw
