### ISSUE TITLE
Aprueba pago rechazado o fallido en banco.

### ISSUE THREAD

**Issue by Patricio-Bustos** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#174]
**Describe el bug**
Al rechazar el pago desde el banco, se procesa como pagada la orden de compra de woocommerce.

Una descripción concisa sobre el bug.

**Para reproducir**

1. Pulsar el boton de pago en la pagina de checkout de woocommerce
2. Selecciona metodo de pago en pasarela de webpay, ingresa datos de tarjeta y pulsa boton pagar.
3. Rechaza el pago en pasarela de banco del pagador
4. Se retorna a pasarela de webpay con mensaje "procesando" y al pasar al resultado de woocommerce, se muestra el mensaje de pago fallido pero woocommerce marca como completado el pedido.

**Comportamiento observado**
Se valida un pago fallido.

**Comportamiento esperado**
El pago fallido debería actuar del mismo modo que el pago anulado.

**Contexto adicional**
Revisando el código, veo que la función getTransactionDetails($result) del controlador de respuesta, inicializa en true la variable $responseCode en caso de que el resultado tenga un response code independiente de que sea 0, -1 u otro, y false en caso de que no exista la variable response code como sucede en el caso de anulacion.

Bloque:
La función response($postData) del archivo ResponseController.php al final registraba un pago rechazado y redireccionaba a la url que validaba el pago de la orden de compra sin ninguna validación para ese caso.

 Evalúa si existe codigo de respuesta o no, no evalúa el valor del código de respuesta. de ahí a que se valida el pago independiente del codigo de respuesta de la transacción. Sólo en caso de anular pago se da el caso de que no existe el parametro responseCode.

**Comment by Patricio-Bustos** [comment]
Bueno, ya que a pesar de que mucha gente ha reportado el mismo problema sin ninguna solución, les comparto la solución que apliqué: 
valide primero el codigo de respuesta de transbank y corregí la url de redirección en caso de pago rechazado. Ojo: El problema ocurre sólo en producción, así que revisen sus integraciones. Saludos a todos! 

![Sin título](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/101227411/13aa6456-c7c8-4608-81e6-a7ffa8286c1e)

**Comment by mastudillot** [comment]
Hola @Patricio-Bustos gracias por avisar, ahora estamos mirando este comportamiento y estamos haciendo varios cambios en el plugin para mejorar algunos flujos. Vamos a considerar tus comentarios en el desarrollo.
