### ISSUE TITLE
Pasarela no es visible

### ISSUE THREAD

**Issue by git1b** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#182]
**Describe el bug**

Al llegar al checkout, la pasarela no es visible

**Para reproducir**

1. Instalar Wordpress
2. Instalar WooCommerce
3. Instalar Transbank webpay plus rest
4. Desactivar HPOS
5. Crear un producto
6. Verificar la moneda en CLP
7. Activar la pasarela
8. Intentar realizar una compra

**Comportamiento observado**

Al llegar al checkout la pasarela no está, no hay errores visibles (no los veo ni activando debug)

Al hacer un diagnostico (que muestra todo OK), encuentro este error en el registro: 2023 12 11, 10:45 am > ERROR > ERROR: cURL error 6: Could not resolve host: tbk-app-y8unz.ondigitalocean.app (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) [] []

**Comportamiento esperado**

La pasarela debería funcionar en modo sandbox

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 1.6.8
- Woocommerce: 8.3.1
- PHP: 8.1.24

**Contexto adicional**

Probé distintas versiones de PHP (7.4 a 8.2), paneles (hestia/cyberpanel) y temas, pero bajo el mismo proveedor (oracle)

**Comment by Matiasnickolas** [comment]
Hola! Hemos visto que se trata de incompatibilidad del plugin con la característica de woocommerce blocks que viene por defecto en las instalaciones nuevas con la versión 8.3 en adelante. 
De momento el plugin no es compatible con esa característica, por lo que si requieres usarlo con version de WC 8.3+, puedes probar 2 opciones:

- Desactivar esta característica en woocommerce -> https://woo.com/document/cart-checkout-blocks-status/?quid=45ea0b3f3148cd2ee97065722bf3e5fb#section-9
- Realizar una instalación de Woocommerce 8.2 y luego actualizar a 8.3 (con esto debería mantenerse la configuración y el plugin seguiría funcionando)

**Comment by git1b** [comment]
ohh gracias Matias! no lo habia visto 
![image](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/129235002/a718565a-b4af-4a9c-bac5-9ae61e6a4bb7)
funcionando después de hacer el cambio
