### ISSUE TITLE
Class WC_PAYMENT_gateway_cc not found

### ISSUE THREAD

**Issue by edofritz** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#203]
No funciona el sitio al activar el plugin

**Capturas de pantalla**

![WhatsApp Image 2024-02-01 at 08 47 23](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/22921690/6bc5b167-56b7-4aec-a88e-c0f7b0d04496)

- Plugin: 1.6.8
- Woocommerce: 7
- PHP: 7.4

**Comment by mastudillot** [comment]
Hola @edofritz tienes tu woocommerce activo, por el error que reportas, pareciera que no está instalado o activo.

**Comment by mastudillot** [comment]
@edofritz liberamos una nueva versión del Plugin, la 1.7.0, puedes probar con esa versión.

**Comment by edofritz** [comment]
Estimados, 

Instale la nueva versión y error persiste

**Comment by Matiasnickolas** [comment]
Tu versión de Woocommerce es 7.0.0?

**Comment by edofritz** [comment]
Ahora tengo la 8.5.2, me recomiendas intentar con alguna en particular?

**Comment by Matiasnickolas** [comment]
Hicimos algunas pruebas con las mismas versiones que utilizas y no se reproduce tu problema. ¿En que momento se genera ese error? ¿Al activar el plugin tu sitio deja de funcionar o logras llegar al checkout? ¿Puedes realizar un diagnóstico desde la pestaña de configuración del plugin? ¿Usas checkout por bloques o clásico? ¿Que versión de wordpress utilizas?

**Comment by edofritz** [comment]
El error se produce al activar el plugin

**Comment by edofritz** [comment]
te adjunto nuevamente el error: 

![image](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/22921690/809d1edd-1abc-4e4d-8529-969cffce509d)

**Comment by mastudillot** [comment]
Hola @edofritz en las pruebas que realizamos, la única manera en la que obtenemos un error similar es cuando hay un problema con Woocommerce, puedes borrar el plugin de forma manual e indicar que otro plugins tienes instalados

**Comment by edofritz** [comment]
Finalmente (lamentablemente) tuve que intervenir el plugin y eliminar ese archivo (ya que no uso la función MALL) al eliminar el archivo también elimine la referencia a él y funcionó

**Comment by mastudillot** [comment]
Lamentamos que llegaras a ese punto, pero nos hubiera ayudado mucho que nos compartieras la configuración que tenías en tu tienda.

Cualquier otra duda nos comentas. Recuerda que puedes unirte a nuestra comunidad de Slack para un soporte más inmediato. https://join.slack.com/t/transbankdevelopers/shared_invite/zt-28qs2s72f-6OxpP3EB73u13ic2F5RduQ
