### ISSUE TITLE
Reembolso compra con Debito

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#209]
Hola,

Los logs del pedido indican error y luego reembolso exitoso.
![Screenshot_20240207_181645_Chrome](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/31737938/4b605be2-4374-45b2-b267-a78d48e50f8a)

Creo que no debería pasar algo así.¿ahora como verifico si esta reembolsado o no?

**Comment by svenms** [comment]
Hola!

Hable con la persona que lo realizo y me dijo que cree que fue 1 sola vez,
aunque ese creo siento que podrían ser 2 veces. ¿En ese caso el flujo
estaría correcto, no?

**Comment by Matiasnickolas** [comment]
Hola @svenms La segunda nota que indica Reembolso exitoso, corresponde a un segundo intento que si se realizó correctamente. Si revisas los logs de ese día seguramente puedas corroborar que hubo un 2do intento.
Para futuros casos de este tipo, puedes consultar el estado de la transacción en Transbank mediante el botón 'Consultar estado de la transacción' (Que es válido para transacciones que tengan hasta 7 días de haber sido creadas)
