### ISSUE TITLE
¿Existe la posibilidad de acceder el proceso de pago en ingles y portugués?

### ISSUE THREAD

**Issue by seschbra** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#225]
Usamos este plug-in en un comercio con clientes de todo el mundo, todo el proceso por nuestra parte esta construido en 3 idiomas. No usamos un plug-in dedicado a hacer WooCommerce multilingue sino usamos los hooks para garantizar que los textos se traducen (los de este plug-in también), pero al pasar a su portal de pago todo está en español. ¿Hay una forma de traspasar el código de idioma con la redirección hacia ustedes para que su portal esté en el idioma del cliente?

**Comment by mastudillot** [comment]
Hola @seschbra el plugin actualmente no cuenta con soporte en otros idiomas, tampoco hay un plan para agregar un idioma secundario.

Por otra parte, aunque el plugin manejara la opción de un segundo idioma, la pasarela de pagos de Transbank se mostraría de igual manera en español, por lo que nunca tendrías la experiencia completa en el idioma que deseas. La pasarela de pago puede cambiar el idioma a inglés siempre y cuando el código de comercio sea para pagos en dólares.

**Comment by mastudillot** [comment]
No se han realizado pruebas, pero no hay imágenes con texto en la pasarela. Lo de usar un traductor es algo que se puede probar, pero no se han realizado pruebas para ver si afecta la experiencia.

Saludos.
