### ISSUE TITLE
Al instalar New Relic, los sitio web quedan con Critial Error

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#226]
Al instalar New Relic con Cyberpanel (Litespeed), los sitios web dejan de funcionar por un error critico en el plugin de Transbank:

> PHP Fatal error:  Uncaught Error: Class "WC_Payment_Gateway_CC" not found in /home/chilevapo.cl/public_html/wp-content/plugins/transbank-webpay-plus-rest/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php:34
> Stack trace:
> #0 /home/chilevapo.cl/public_html/wp-content/plugins/seo-by-rank-math-pro/vendor/composer/ClassLoader.php(576): include()
> #1 /home/chilevapo.cl/public_html/wp-content/plugins/seo-by-rank-math-pro/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
> #2 /home/chilevapo.cl/public_html/wp-includes/plugin.php(130): Composer\Autoload\ClassLoader->loadClass()
> #3 /home/chilevapo.cl/public_html/wp-includes/plugin.php(442): add_filter()
> #4 /home/chilevapo.cl/public_html/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php(48): add_action()
> #5 /home/chilevapo.cl/public_html/wp-settings.php(517): include_once('...')
> #6 /home/chilevapo.cl/public_html/wp-config.php(85): require_once('...')
> #7 /home/chilevapo.cl/public_html/wp-load.php(50): require_once('...')
> #8 /home/chilevapo.cl/public_html/wp-login.php(12): require('...')
> #9 {main}
>   thrown in /home/chilevapo.cl/public_html/wp-content/plugins/transbank-webpay-plus-rest/src/PaymentGateways/WC_Gateway_Transbank_Oneclick_Mall_REST.php on line 34
> 

Al desactivar el plugin de Transbank, ningun problema.

Php 8.0
Wordpress 6.5
Woocommerce 8.7.0
Plugin Tranbank: 1.8.0
Cyberpanel Litespeed 2.3.5

**Comment by mastudillot** [comment]
Hola @svenms se ha revisado lo que nos comentas, pero no logramos reproducir el error, ¿tú lograste resolverlo?

El error Uncaught Error: Class "WC_Payment_Gateway_CC" not found, dice que no se encuentra una clase, esta clase es de Woocommerce, por lo que la única forma de que de ese error es que exista un problema en la instalación de tu sitio.

Si nos pudieras aportar más detalles te lo agradeceríamos.

**Comment by svenms** [comment]
Te hablé por Inbox de Facebook para darte acceso a un Staging.
La unica solución que logré fue ir al archivo que llamaba a WC_Payment_Gateway_CC y eliminar esa línea en el plugin.

**Comment by mastudillot** [comment]
Probando en el entorno que compartiste, se encontró el problema, esto quedara resuelto en la siguiente versión del plugin.
