### ISSUE TITLE
No se procesan los pedidos de WooCommerce

### ISSUE THREAD

**Issue by JaimeSoporteCHM** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#245]
**Describe el bug**

al intentar comprar en la web con webpay, la compra no se efectua lanzando error

ERROR:
2024-06-17 16:07:48 +00:00 > INFO > BUY_ORDER: _Healthcheck_ => Preparando datos antes de crear la transacción en Transbank => data: {"sessionId":"66705f545e58a","amount":990,"returnUrl":"http:\/\/test.com\/test","environment":"LIVE","commerceCode":"5970xxxx9368"} [] []
2024-06-17 16:11:09 +00:00 > INFO > BUY_ORDER: _Healthcheck_ => Preparando datos antes de crear la transacción en Transbank => data: {"sessionId":"6670601dbff2e","amount":990,"returnUrl":"http:\/\/test.com\/test","environment":"LIVE","commerceCode":"5970xxxx9368"} [] []

al momento de realizar la comprobacion de conexion, esta queda sin devolver respuesta y esto aparece en el log

Información de Plugin / Ambiente

Software E-commerce: woocommerce
Version E-commerce: 8.9.3
Versión actual del plugin: 1.9.1

Última versión del plugin:
Estado de la Extensiones de PHP
Información Principal

Software Servidor: LiteSpeed

Estado de PHP:
WARN: El plugin no ha sido testeado con esta version
Versión: 8.1.29
Extensiones PHP requeridas
Extensión	Estado	Versión
json	OK	8.1.29
dom	OK	20031129
curl	OK	8.1.29

**Comment by mastudillot** [comment]
Hola, puedes intentar usando esta otra versión del Plugin [transbank-webpay-plus-rest-guzzle7.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases/download/1.9.1/transbank-webpay-plus-rest-guzzle7.zip)

**Comment by JaimeSoporteCHM** [comment]
cual es la diferencia entre las versiones? esto paso de un dia para otro

**Comment by JaimeSoporteCHM** [comment]
Fatal error: Cannot redeclare woocommerceTransbankInit() (previously declared in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php:106) in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/webpay-rest.php on line 113

me salta este error

**Comment by mastudillot** [comment]
Debe ser un conflicto con otro plugin que esta utilizando una versión más actualizada de guzzle, que es una dependencia del plugin. Me avisas si te ayuda.

**Comment by JaimeSoporteCHM** [comment]
desactive oficial, active el que tu indicas y sigue pegado el error en el log, no avanza a la verificacion de conexion

2024-06-17 16:37:14 +00:00 > INFO > BUY_ORDER: _Healthcheck_ => Preparando datos antes de crear la transacción en Transbank => data: {"sessionId":"6670663a9d5c1","amount":990,"returnUrl":"http:\/\/test.com\/test","environment"

sigue en ese paso y no avanza mas

**Comment by mastudillot** [comment]
Nos compartes el log de WordPress? la ubicación es wp-content/uploads/wc-logs, busca alguno que tenga el nombre de fatal-errors.

Revisa que no tenga alguna información privada antes de mandarlo, como credenciales o cosas que sean importantes de tu comercio.

**Comment by mastudillot** [comment]
> Fatal error: Cannot redeclare woocommerceTransbankInit() (previously declared in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php:106) in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/webpay-rest.php on line 113
> 
> me salta este error

Este error al parecer es porque no eliminaste el plugin anterior, dice que no puede volver a declarar una función que ya estaba declarada.

Debes desactivar y eliminar el plugin anterior.

**Comment by JaimeSoporteCHM** [comment]
> Nos compartes el log de WordPress? la ubicación es wp-content/uploads/wc-logs, busca alguno que tenga el nombre de fatal-errors.
> 
> Revisa que no tenga alguna información privada antes de mandarlo, como credenciales o cosas que sean importantes de tu comercio.

2024-06-17T16:34:48+00:00 CRITICAL Cannot redeclare woocommerceTransbankInit() (previously declared in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php:106) CONTEXT: {"error":{"type":64,"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/transbank-webpay-plus-rest-guzzle7\/webpay-rest.php","line":113},"backtrace":[{"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/woocommerce\/includes\/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}

2024-06-17T16:37:14+00:00 CRITICAL Declaration of GuzzleHttp\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string CONTEXT: {"error":{"type":64,"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/transbank-webpay-plus-rest-guzzle7\/vendor\/guzzlehttp\/psr7\/src\/Request.php","line":59},"backtrace":[{"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/woocommerce\/includes\/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}

2024-06-17T17:05:15+00:00 CRITICAL Cannot redeclare woocommerceTransbankInit() (previously declared in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/webpay-rest.php:106) CONTEXT: {"error":{"type":1,"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/transbank-webpay-plus-rest\/webpay-rest.php","line":106},"backtrace":[{"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/woocommerce\/includes\/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}

2024-06-17T17:08:31+00:00 CRITICAL Declaration of GuzzleHttp\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string CONTEXT: {"error":{"type":64,"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/transbank-webpay-plus-rest-guzzle7\/vendor\/guzzlehttp\/psr7\/src\/Request.php","line":59},"backtrace":[{"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/woocommerce\/includes\/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}

esto aparece en el log de error critico

**Comment by mastudillot** [comment]
> > Nos compartes el log de WordPress? la ubicación es wp-content/uploads/wc-logs, busca alguno que tenga el nombre de fatal-errors.
> > Revisa que no tenga alguna información privada antes de mandarlo, como credenciales o cosas que sean importantes de tu comercio.
> 
> 2024-06-17T16:34:48+00:00 CRITICAL Cannot redeclare woocommerceTransbankInit() (previously declared in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php:106) CONTEXT: {"error":{"type":64,"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/webpay-rest.php","line":113},"backtrace":[{"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/woocommerce/includes/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}
> 
> 2024-06-17T16:37:14+00:00 CRITICAL Declaration of GuzzleHttp\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string CONTEXT: {"error":{"type":64,"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/vendor/guzzlehttp/psr7/src/Request.php","line":59},"backtrace":[{"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/woocommerce/includes/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}
> 
> 2024-06-17T17:05:15+00:00 CRITICAL Cannot redeclare woocommerceTransbankInit() (previously declared in /home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/webpay-rest.php:106) CONTEXT: {"error":{"type":1,"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest/webpay-rest.php","line":106},"backtrace":[{"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/woocommerce/includes/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}
> 
> 2024-06-17T17:08:31+00:00 CRITICAL Declaration of GuzzleHttp\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string CONTEXT: {"error":{"type":64,"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/vendor/guzzlehttp/psr7/src/Request.php","line":59},"backtrace":[{"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/woocommerce/includes/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}
> 
> esto aparece en el log de error critico

Es por lo que te comente, elimina el plugin de Transbank (**No desactivar**) e instalas el que te deje antes.

**Comment by JaimeSoporteCHM** [comment]
elimine los 2 plug y luego instale el que tu indicas antes de enviarte ese log, alguna forma de comunicarme mas directo con ustedes?

**Comment by JaimeSoporteCHM** [comment]
2024-06-17T19:30:55+00:00 CRITICAL Declaration of GuzzleHttp\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string CONTEXT: {"error":{"type":64,"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/transbank-webpay-plus-rest-guzzle7\/vendor\/guzzlehttp\/psr7\/src\/Request.php","line":59},"backtrace":[{"file":"\/home\/chilemontanna\/public_html\/webs\/chilemontana.cl\/wp-content\/plugins\/woocommerce\/includes\/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}

el log que acabo de generar, eso es al momento de verificar conexion con transbank desde el menu diagnostico

**Comment by mastudillot** [comment]
> elimine los 2 plug y luego instale el que tu indicas antes de enviarte ese log, alguna forma de comunicarme mas directo con ustedes?

Hola, si, tenemos una comunidad en Slack, te dejo el [link de invitación](https://transbankdevelopers.slack.com/join/shared_invite/zt-2geuipcoy-xB0u6vsI_DuVYh41b8hhjA#/shared-invite/email), puedes hacer referencia a este issue de github.

**Comment by mastudillot** [comment]
> 2024-06-17T19:30:55+00:00 CRITICAL Declaration of GuzzleHttp\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string CONTEXT: {"error":{"type":64,"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/transbank-webpay-plus-rest-guzzle7/vendor/guzzlehttp/psr7/src/Request.php","line":59},"backtrace":[{"file":"/home/chilemontanna/public_html/webs/chilemontana.cl/wp-content/plugins/woocommerce/includes/class-woocommerce.php","line":350,"function":"critical","class":"WC_Logger","type":"->"},{"function":"log_errors","class":"WooCommerce","type":"->"}]}
> 
> el log que acabo de generar, eso es al momento de verificar conexion con transbank desde el menu diagnostico

Vale, entonces el problema es más complicado, te recomiendo desactivar todos los plugins y dejar solo los de WoocCommerce y Transbank y ver si te funciona, luego ir activándolos 1 a 1 para ver cuál es el que da problemas y con eso nosotros poder revisar si es posible hacerlos compatibles.

**Comment by JaimeSoporteCHM** [comment]
es un sitio en produccion... hacer eso seria catastrofico a nivel de ventas.... el plugin de flow funciona perfecto y el de ustedes dejo de funcionar de un momento a otro... si quieres te envio el listado de plugins del sitio web para saber si tienen alguna incompatibilidad, pero el cuello se produce que el plug de tbk no conecta desde woo hacia sus servidores, el resto da todo ok

**Comment by mastudillot** [comment]
Ok, si no tienes forma de poder hacer lo anterior, quedamos en una encrucijada, ya que sí no podemos instalar todos los plugins de tu lista. No vamos a poder saber cuál da el problema. Lo otro, que no te funcione el plugin de Transbank, no significa que nuestro plugin sea el del problema. Hay otros plugins que pueden generar la incompatibilidad por la forma en la que están programados.

Lo que si, toda información que nos des es útil, así que si nos ayudas con la lista nos ayudara igualmente.

**Comment by JaimeSoporteCHM** [comment]
Envio listado de plugins:

Ajax Load More
Akismet Anti-spam: Spam Protection
Añade Ajax al carrito para WooCommerce
B2BKing Core
B2BKing Pro
BEAR - Editor por lotes y gestor de productos profesional para WooCommerce
Better Search Replace
Block Emails for WooCommerce
Booster Plus for WooCommerce
Checkout Field Editor for WooCommerce (Pro)
Cities Shipping Zones for WooCommerce
Colorlib Login Customizer
Contact Form 7
Contact Form CFDB7
Editor clásico
Email Customizer for WooCommerce
Facebook for WooCommerce
FiboSearch - AJAX Search for WooCommerce (Pro)
Flow Payment
GenTime
Google Listings and Ads
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress
Index WP MySQL For Speed
IndexNow
Jetpack
Joinchat
LiteSpeed Cache
Loco Translate
Mailchimp for WooCommerce
Max Mega Menu
Max Mega Menu - Pro Addon
Menu Caching
Mercado Pago
Metricool
Multi-Step Checkout for WooCommerce (Pro)
Perfect Brands for WooCommerce
Performant Translations
Productos de impresión de WooCommerce
Rank Math SEO PRO
Rank Math SEO with AI SEO Tools
Real Category Management
Really Simple SSL
Simple Custom Post Order
Site Kit by Google
SiteOrigin CSS
TablePress
Thank You Page Customizer for WooCommerce
Transbank Webpay REST
UpdraftPlus - Backup/Restore
weLaunch Framework
WooCommerce
Woocommerce Bsale V2
WooCommerce Cart Abandonment Recovery
WooCommerce Order Status & Actions Manager
WooCommerce Super Shipping
WooCommerce.com Update Manager
Wordfence Security
WP-Memory-Usage
WPCode Lite
WPS Hide Login
YITH Request a Quote for WooCommerce Premium
YITH WooCommerce Minimum Maximum Quantity Premium
YITH WooCommerce Order & Shipment Tracking Premium

**Comment by JaimeSoporteCHM** [comment]
que otra info puedo entregarte para ir viendo que sucede? si quieres podemos enviar mas info "sensible" via correo, mi mail es jaime@chilemontana.cl

**Comment by JaimeSoporteCHM** [comment]
@mastudillot creo que encontre el error... es el plugin Productos de impresión de WooCommerce, https://welaunch.io/ pueden chequear donde esta el problema?

**Comment by mastudillot** [comment]
Vale, estamos viendo como poder obtener ese Plugin

**Comment by Eduufariasdiaz** [comment]
Tengo un error parecido con el plugins OPEN POS, realizando pruebas ese fue el plugins que no me deja procesar con transbank, me sale el siguiente error "SE PRODUJO UN ERROR AL PROCESAR TU PEDIDO. COMPRUEBA SI HAY CARGOS EN TU MÉTODO DE PAGO Y REVISA TU [HISTORIAL DE PEDIDOS](https://americanhood.cl/mi-cuenta/orders/) ANTES DE VOLVER A REALIZAR EL PEDIDO." , realice prueba intalando el plugins de FLOW como pasarela de pago y si me funciono perfecto

**Comment by 2xffwd** [comment]
Yo tambien tengo problemas similares a los que describe el post original y tambien encontre que el conflicto era con OpenPOS. Hay algo que les pueda proporcionar para ayudar a corregir el problema de compatibilidad? Instalando el plugin con la version anterior de guzzle no soluciona el conflicto.

**Comment by JaimeSoporteCHM** [comment]
Hasta el momento lo unico que pude hacer es quitar el plug... no tienen opcion de cambiarlo por otro?

**Comment by 2xffwd** [comment]
ninguna posibilidad, es parte fundamental de nuestro negocio

**Comment by Eduufariasdiaz** [comment]
Me ocurre lo mismo, ninguna posibilidad en quitar OpenPOS porque es fundamental para mi negocio, en ese caso mejor cambiar el plugins de transbank por el de flow que si funciona.

**Comment by JaimeSoporteCHM** [comment]
tambien funciona el de mercado pago, para su info!

**Comment by truchosky** [comment]
a mi ahora me pasa con pixelyoursite, el mismo error de guzle, el único plugin con problemas es el de transbank

**Comment by mastudillot** [comment]
Vamos a sacar una versión que ya no de problemas que ya no usara guzzle dentro de poco

**Comment by mastudillot** [comment]
Hola, la última versión ya no debería dar problemas.

https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases/latest

**Comment by JaimeSoporteCHM** [comment]
Hola mauricio, junto con saludar, quisiera saber si ya pudieron actualizar
la version de transbank para woocommerce sin la libreria de guzzle, para
que no me genere conflictos!

espero tus comentarios, saludos


--
Jaime Daveggio C.

Webmaster Chilemontana.cl

Productor Gráfico UI/UX Senior

Desarrollador WEB
[image: mobilePhone] +569 6833 8899 <+569+6833+8899>
[image: website] www.chilemontana.cl
[image: address] Carlos XII 120, Local E - Las Condes
*Síguenos en nuestras redes sociales: Instagram Deportivo
<https://www.instagram.com/chilemontanacl/> / Instagram Industrial
<https://www.instagram.com/chilemontanaindustrial/> / LinkedIn
<https://www.linkedin.com/company/chilemonta%C3%B1a/>*
