### ISSUE TITLE
NO SE INGRESA A LA PLATAFORMA DE PAGO DE TRANSBANK POR WOOCOMMERCE

### ISSUE THREAD

**Issue by Eduufariasdiaz** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#246]
"SE PRODUJO UN ERROR AL PROCESAR TU PEDIDO. COMPRUEBA SI HAY CARGOS EN TU MÉTODO DE PAGO Y REVISA TU [HISTORIAL DE PEDIDOS](https://americanhood.cl/mi-cuenta/orders/) ANTES DE VOLVER A REALIZAR EL PEDIDO."

No abre la plataforma de pago, genera la orden y en sistema de woocommerce dice pendiente a pago, pero no abre la plataforma de pago al momento de tratar de realizar dicho pago, el plugins que me da este error es con el OPEN POS, probe con pasarela de pago de FLOW y si me da opción para poder pagar, estoy usando PHP 8.0 , 8.1 , 8.2 Y 8.3 y en todas dio error.

**Comment by matiasweb** [comment]
Información del sitio:

WordPress 6.5.5
WooCommerce 9.0.2
Incompatibilidad con plugin Open POS 6.5.7 https://codecanyon.net/item/openpos-a-complete-pos-plugins-for-woocomerce/22613341

error_log:
PHP Fatal error:  Declaration of GuzzleHttp\Psr7\Request::getRequestTarget() must be compatible with Psr\Http\Message\RequestInterface::getRequestTarget(): string in /home/yfesdrry/public_html/wp-content/plugins/transbank-webpay-plus-rest/vendor/guzzlehttp/psr7/src/Request.php on line 59

cc: @mastudillot 

Ya probamos con esta versión:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases/download/1.9.1/transbank-webpay-plus-rest-guzzle7.zip

Y no funcionó. ¿Alguna idea de qué podría estar pasando?

**Comment by mastudillot** [comment]
Hola, si ya probaron con esa versión, no hay mucho más que puedan hacer, estamos trabajando en sacar una versión con soporte a PHP 8 que ya pueda usar guzzle7 por defecto,  y evitar tener dos versiones y lograr que sea compatible con otros plugins

**Comment by mastudillot** [comment]
Hola, la última versión ya no debería dar problemas.

https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases/latest
