### ISSUE TITLE
Pedido en estado "Procesando" y reconocido como "pagado" pero sin transacción

### ISSUE THREAD

**Issue by felipebrunet** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#247]
**Describe el bug**
En sitio Woocommerce cayó ayer un pedido sin detalles de transacción, con el plugin WebPay Plus.
Hoy PM voy a reproducir el error, pero he dejado desactivado el plugin de momento.

**Para reproducir**
Lo voy a completar hoy PM

**Comportamiento observado**
La compra es reconocida como completa por Woocommerce.

**Comportamiento esperado**
La compra debe ser cancelada por Woocommerce.

**Capturas de pantalla**
![image](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/assets/40004928/d7cdf23f-6e54-4b76-ad68-0e24f1ff4b7e)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 1.9.1
- Woocommerce: 9.0.2
- PHP: 8.1.13
- Wordpress 6.5.5

**Contexto adicional**
La tienda tiene horario de cierre a las 21:00. Y justo la compra se hizo a esa hora ayer.

**Comment by mastudillot** [comment]
Con la información proporcionada no podemos analizar un posible problema, se ha realizado mejoras en las últimas versiones respecto a los flujos de pago. Considerar probar con esta versión y crear una nueva issue en caso que se mantenga el comportamiento.
