### ISSUE TITLE
compatibilidad con woocommerce blocks

### ISSUE THREAD

**Issue by undermix** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#25]
Estimados buen dia, seria bueno que el plugins fuera compatible con woocommerce blocks, el formulario de este plugins es mas moderno y cómodo pero no es compatible la forma de pago,Saludos.

**Comment by gonzunigad** [comment]
Hola @undermix . ¿Nos podrías explicar con mayor detalle que hay que hacer para hacerlo compatible o que problema tienes que hace que no sea compatible ahora?

**Comment by gonzunigad** [comment]
Hola @undermix vamos a sacar un nuevo release, si me comentas más detalles sobre esto quizás pueda incluirlo.

**Comment by undermix** [comment]
WooCommerce Block nos permitE insertar una sección de productos de WooCommerce en el contenido de WordPress mediante un bloque de contenido, muy visual, pero al agregar el bloque de cart no aparece el metodo de pago webpay, pero si usamos la pag de cart normal si aparece. adjunto imagen del bloque
![Captura de Pantalla 2020-12-21 a la(s) 23 12 15](https://user-images.githubusercontent.com/7454445/102840615-045ff700-43e2-11eb-90ed-9621f91bc6ef.png)
.

**Comment by gonzunigad** [comment]
¿y eso no es una configuración que puedas gestionar dentro del plugin de blocks?
¿Otros medios de pago aparecen ahí?

**Comment by gonzunigad** [comment]
Cerraré este issue por no tener respuesta. Si llega alguna respuesta sobre las últimas dudas, encantado de volver a abrirlo. 
Saludos!

**Comment by mstanleyb** [comment]
Hola!

[Estos son los medios de pagos](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/) que funcionan actualmente con WooCommerce Blocks.

Al parecer funciona de manera distinta al tradicional checkout de Woo, ya que efectivamente no aparece webpay disponible como opción al crear el checkout con el "bloque de checkout" de WooCommerce Blocks.

Este checkout se acerca de mejor manera a las buenas prácticas de un buen checkout (como hace shopify por ejemplo), sería un plus que en un futuro pueda estar funcionando tambien con estos Blocks

Gracias @gonzunigad por el gran avance que han logrado junto al equipo en el desarrollo de esta integración
