### ISSUE TITLE
Error en página Resumen de compra

### ISSUE THREAD

**Issue by PilasChile** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#261]
Cada transacción exitosa hecha con transbank web pay no se enlaza con la página de Exito en tu compra configurada con Elementor Pro como pagina de resumen o repositario de compra, En vez de hacer esto me lanza un error critico con el siguiente link https://pilaschile.cl/?elementor_library=exito-en-tu-compra%2Forder-received%2F2669%2F&key=wc_order_VEATjPglUyGi6

he reinstalado la api Transbank, actualizado Elementor y woocommerce pero el error persiste 

![image](https://github.com/user-attachments/assets/be64e74c-e881-4626-bdff-72462992f054)

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: Transbank API Versión 1.9.3
- Woocommerce 9.3.3 
- Elementor 3.25.2

**Contexto adicional**

Quizas alguna forma de trabajar sin resumen de compra, o algun plugin que redirija forzosamente a resumen de compra

**Comment by mastudillot** [comment]
La url de exito normalmente es similar a esta: /finalizar-compra/order-received/414/?key=wc_order_UIGMJnIM5dvId

Esta URL se obtiene de forma dinámica al crear la transacción. Es muy problable que el problema este en la configuración de tu vista de finalizar compra.

Para poder guiarte mejor, comparte el log de una transacción.

**Comment by mastudillot** [comment]
Voy a cerrar el issue, si te pasa nuevamente, puedes crear otro y hacer referencia a este.
