### ISSUE TITLE
Pestaña "Webpay Plus" en Dashboard General

### ISSUE THREAD

**Issue by carlosromanxyz** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#28]
Estimados:

Considero que el lugar donde dejaron la pestaña de "Webpay Plus" es incorrecto y merece ser movido como sub elemento a WooCommerce, ya que esta no tiene relevancia para el resto del sitio en general y depende netamente de WooCommerce.

Deben considerar que los elementos primarios, tienen mucha relevancia en la gestión del sitio, trabajan por si solos, pero cuando un plugin es complemento de otro, sus opciones son agrupadas bajo el elemento principal.

En este caso es válido mover al menú WooCommerce > Webpay Plus. 

Ejemplo práctico:

![Product-CSV-Import-Suite-Import-Variations](https://user-images.githubusercontent.com/20117120/102623509-5c1c0b00-4121-11eb-8863-881d6ea19007.png)

CSV Import Suite depende de WooCommerce para su funcionamiento.

**Comment by gonzunigad** [comment]
+1. Probablemente el el próximo release lo movamos de lugar.

**Comment by gonzunigad** [comment]
Este PR soluciona el problema: https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/pull/31

![image](https://user-images.githubusercontent.com/1103494/102712987-aa591780-42a3-11eb-88c3-f183d51c2cf8.png)
