### ISSUE TITLE
Guzzle incompatible con Plugin de Correos de Chile para Etiquetas

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#29]
Estimados,

Al instalar el plugin en la versión 1.3, rompe la generación de etiquetas (PDF) por parte del plugin de Correos de Chile.

[20-Dec-2020 04:28:49 UTC] PHP Fatal error:  Uncaught Error: Undefined class constant 'MAJOR_VERSION' in /home/chilevapo.cl/public_html/wp-content/plugins/transbank-webpay-plus-rest/vendor/guzzlehttp/guzzle/src/Utils.php:118
Stack trace:
#0 /home/chilevapo.cl/public_html/wp-content/plugins/transbank-webpay-plus-rest/vendor/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent()
#1 /home/chilevapo.cl/public_html/wp-content/plugins/correos_chile/includes/guzzle/vendor/guzzlehttp/guzzle/src/Client.php(202): GuzzleHttp\default_user_agent()
#2 /home/chilevapo.cl/public_html/wp-content/plugins/correos_chile/includes/guzzle/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client->configureDefaults()
#3 /home/chilevapo.cl/public_html/wp-content/plugins/correos_chile/includes/api_etiqueta.php(243): GuzzleHttp\Client->__construct()
#4 /home/chilevapo.cl/public_html/wp-content/plugins/correos_chile/includes/api_etiqueta.php(121): correoschile_generar_etiqueta()
#5 /home/chilevapo.cl/public_html/wp-includes/class-wp-hook.php(287): corre in /home/chilevapo.cl/public_html/wp-content/plugins/transbank-webpay-plus-rest/vendor/guzzlehttp/guzzle/src/Utils.php on line 118

Al desactivar el plugin de Transbank, vuelve a operar normalmente.
Se le ha informado a los desarrolladores de Correos de Chile sobre el problema: hector.olivares@correos.cl dejo el contacto aquí por si requieren algún contacto directo.

Saludos cordiales,

**Comment by gonzunigad** [comment]
Esto es debido a que el plugin de Correos usa una versión de Guzzle más antigua. Veo estas posibles soluciones: 
- Idealmente correos de chile podría actualizar Guzzle a la 7.X
- Puedes crear tu propia versión del plugin de Webpay que use la versión 6.x (la misma que usa correos) - Esto es bastante simple. Adjunto una versión que usa Guzzle 6.X en vez de la 7.X
[transbank-webpay-plus-rest.zip](https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/files/5720887/transbank-webpay-plus-rest.zip)

**Comment by svenms** [comment]
Muchas gracias Gonzalo! te agradezco tu ayuda. 
Actualicé la carpeta de Guzzle con la versión 7 de Transbank y funcionó excelente.

Saludos y te agradezco por responder un día no hábil!
