### ISSUE TITLE
HTTP code 422 

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#49]
Intentamos reversar parcialmente una compra del 24/12/2020, pero obtenemos el siguiente mensaje de error:

`Error al anular: Could not obtain a response from the service: Unknown (HTTP code 422). Details: Debit or prepaid transactions only allow reverses, not nullifications.`

Versión del plugin 1.3.3 (última)
Woocommerce 4.7.1

Quedamos atentos para saber a qué se debe este mensaje

**Comment by gonzunigad** [comment]
Hola, tal y como dice el mensaje, débito y prepago solo acepta reversas y nu anulaciones. 
Reversas son refunds del monto total de la compra hasta 30 minutos después del pago. Después de 30 minutos, ya no son reversas y pasan a ser anulaciones. 

Más detalles: https://transbankdevelopers.cl/documentacion/webpay-plus#reversar-o-anular-una-transaccion
