### ISSUE TITLE
Entregar documento PDF en Reversas

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#50]
Estimados, tenemos 2 propuestas:

1- Anteriormente cuando se generara una reversa por el Portal Transbank, se generaba un PDF el cual podía ser enviado al cliente para su tranquilidad y seriedad.
Sería ideal poder contar con un documento similar al realizar una reversa desde Woocommerce. Dado que el plugin ya cuenta con Guzzle, creo que no requeriría tanto desarrollo.

2- Sería ideal poder modificar la descripción del método de pago en Checkout, de modo de que el comercio pueda agregar datos como cantidad de cuotas sin interés que tienen.

Saludos y muchas gracias!

Sven

**Comment by gonzunigad** [comment]
Gracias @svenms por tus propuestas. Tienen bastante sentido así que trataremos de abordarlas. Si quieres apoyarnos con alguna de ellas, avísanos para organizarnos o apoyarte de alguna forma.
