### ISSUE TITLE
Fatal error al instalar/activar

### ISSUE THREAD

**Issue by fserrano88** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#51]
**Describe el bug**

Al intentar activar el plugin descargado siguiendo los pasos de la documentación, es decir: Agregar nuevo plugin->"Transbank Webpay Plus REST", me arrojó el siguiente error:

"El Plugin no pudo ser activado porque provocó un error fatal.

Fatal error: Uncaught Error: Class 'SoapClient' not found in ../plugins/transbank-webpay-plus-rest/src/Telemetry/PluginVersion.php:25 

Stack trace: #0 ../plugins/transbank-webpay-plus-rest/webpay-rest.php(199): Transbank\WooCommerce\WebpayRest\Telemetry\PluginVersion->__construct() #1 ../plugins/transbank-webpay-plus-rest/webpay-rest.php(378): WC_Gateway_Transbank_Webpay_Plus_REST->registerPluginVersion() #2 ../wp-includes/class-wp-hook.php(287): transbank_webpay_rest_on_webpay_rest_plugin_activation('') #3 ../wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 ../wp-includes/plugin.php(484): WP_Hook->do_action(Array) #5 ../wp-admin/plugins.php(193): do_action('activate_transb...') #6 {main} thrown in ../plugins/transbank-webpay-plus-rest/src/Telemetry/PluginVersion.php on line 25"

OBS: Oculté el path completo en el error copiado previamente. 

En este proyecto, no habíamos instalado el plugin antiguo, es el primer intento de integración (proyecto nuevo). Tampoco en este servidor se ha implementado algún otro sitio con Transbank.

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 1.3.3
- Woocommerce: 4.9.0
- PHP: 7.2.24

**Contexto adicional**

Encuentro raro que requiera el SOAPClient, siendo que para este plugin entiendo que no se necesita. En otras integraciones antiguas que habíamos hecho recordaba que estaba en los requerimientos, pero este plugin REST es primera vez que lo intentamos utilizar.

Cualquier idea del error, antes de seguir probando cosas, se los agradecería.

**Comment by gonzunigad** [comment]
Hola! Debes instalar la extensión ext-soap de PHP. Con eso se arregla

**Comment by fserrano88** [comment]
> Hola! Debes instalar la extensión ext-soap de PHP. Con eso se arregla

Muchas gracias. Efectivamente con eso pude activarlo.

La pregunta que tengo, ¿es esperable que ocurra esto? 
Me suena algo inconsistente que el nuevo plugin REST busque evitar usar SOAP, pero que al mismo tiempo requiera la instalación de la extensión ext-soap o arrojé un error.

Si es algo esperado, debiera estar en los requerimientos. 
Si no, bueno debiera corregirse en alguna versión futura.

Muchas gracias!.

**Comment by gonzunigad** [comment]
Hola! Este tema debe haber quedado resuelto en el último release 1.3.4 que lanzamos recién. ¿Me ayudas a confirmar si está nueva versión ya no requiere de ext-soap?

**Comment by fserrano88** [comment]
> Hola! Este tema debe haber quedado resuelto en el último release 1.3.4 que lanzamos recién. ¿Me ayudas a confirmar si está nueva versión ya no requiere de ext-soap?

Efectivamente, funciona bien en la 1.3.4. Detallo los pasos:
1) phpdismod soap (restart apache)
2) la versión 1.3.3 volvió a presentar el error al activar.
3) Actualice el plugin a versión 1.3.4
4) Me dejo activar correctamente
5) Probé con una transacción en producción y todo OK.

Gracias,
Saludos.
