### ISSUE TITLE
Soporte USD plugin WooCommerce

### ISSUE THREAD

**Issue by diegusleik** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#56]
Buenas,

El plugin [WooCommerce | Plugin Webpay Plus](https://www.transbankdevelopers.cl/plugin/woocommerce/#) está construído para operar únicamente con CLP. Sin embargo, Webpay Plus permite operar con USD. Sería ideal que esta moneda esté integrada en el plugin.

Saludos

**Comment by truchosky** [comment]
pero no que transbank cobra en peso chileno igual?, y hace la conversion del cliente a usd??, o también cobra en usd sin ningun tipo de conversión?

**Comment by gonzunigad** [comment]
También puede cobrar en USD directamente. El código de comercio debe estar configurado para eso.
