### ISSUE TITLE
Nivel 2 de los de códigos de respuesta de autorización

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#59]
Hola, espero que estén muy bien. 

Una consulta específica, sabes si al activar el Nivel 2 de los de códigos de respuesta de autorización, estos se muestran en el resultado en backend en el plugin de Woocommerce?

Saludos!

**Comment by ffiebig** [comment]
No sé a que te refieres con el Nivel 2 de códigos de respuesta de autorización. Me lo aclaras ?

Quizás @gonzunigad se maneja en esto

**Comment by svenms** [comment]
Hola!

Son los siguientes que se están habilitando [https://www.transbankdevelopers.cl/producto/webpay#codigos-de-respuesta-de-autorizacion](https://www.transbankdevelopers.cl/producto/webpay#codigos-de-respuesta-de-autorizacion)

**Comment by gonzunigad** [comment]
Hola. Se muestran como código de respuesta, sin mayor detalle, al igual que los de Nivel 1 :)
