### ISSUE TITLE
Woocommerce Blocks Checkout

### ISSUE THREAD

**Issue by TOPAiiN** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#60]
Hola, 
Quisiera saber si es posible integrar el plugin con Woocommerce Blocks. Estos últimos dan un _look_ más amigable para el cliente a la hora de finalizar la compra, más parecido a Shopify. Sin embargo, probando con dos sitios creados en Woocommerce tuve inconvenientes de que al finalizar no salía Webpay como método de pago aún teniendo la moneda en CLP. Al usar el _checkout_ normal de WC todo funciona sin problemas.
Gracias de antemano.

[Documentación Woocommerce Blocks](https://docs.woocommerce.com/document/woocommerce-blocks/)
[Status Woocommerce Blocks](https://docs.woocommerce.com/document/cart-checkout-blocks-support-status/)

**Comment by gonzunigad** [comment]
Hola! Podemos revisar esto. ¿Sabes que hay que hacer para que aparezca?

**Comment by gonzunigad** [comment]
Leyendo, se indica que solo soporta Métodos de pago oficiales y que el API para que los métodos de pago puedan implementarse no es final y está sujeta a cambios.

**Comment by gonzunigad** [comment]
Cerraré este issue hasta que eso esté maduro y exista documentación.

**Comment by TOPAiiN** [comment]
Gracias, Gonzalo. Espero que se pueda integrar en el futuro entonces.
