### ISSUE TITLE
Información de Reversas está incompleta en Notas del Pedido 

### ISSUE THREAD

**Issue by svenms** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#68]
Estimados,

Sería ideal que la información relacionada a la reversa también se indique en las Notas del Pedido, pues actualmente no se agrega la información de Autorización, fecha, etc.. como se puede ver en la [Siguiente Imagen](https://ibb.co/THWxXwz).

Saludos cordiales!

Sven Moller

**Comment by gonzunigad** [comment]
Hola! Esa es toda la información que llega del API de Transbank. El Plugin no filtra nada.
