### ISSUE TITLE
Error Crítico con plugins Google Listings & Ads

### ISSUE THREAD

**Issue by dsalgadoh** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#71]
Buenas tardes, favor ayuda con este error.
Parece ser un problema de versiones Guzzle ?

https://1drv.ms/u/s!AoPeNq5wywD_lNZRgBvMiVNlRf5d1g?e=Ahqa94

**Comment by gonzunigad** [comment]
Hola, si, es problema el Guzzle. Puedes, eventualmente, crear tu propia versión del plugin usando otra vesión de Guzzle (5, 6 o 7) y debería funcionar sin problema.

**Comment by gonzunigad** [comment]
Ahora estamos dejando una versión especial del plugin que puedes instalar manualmente si es que tienes este problema. https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/releases

Bajar la versión transbank-webpay-plus-rest-guzzle7.zip
