### ISSUE TITLE
Error crítico con plugins Google Listings & Ads

### ISSUE THREAD

**Issue by dsalgadoh** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#72]
Buenas tardes, favor ayuda con este error.
Parece ser un problema de versiones Guzzle ?

https://1drv.ms/u/s!AoPeNq5wywD_lNZRgBvMiVNlRf5d1g?e=Ahqa94

**Comment by gonzunigad** [comment]
Sip, al no son compatibles las versiones de guzzle que los plugins usan. Debes elegir entre uno u otro.

**Comment by dsalgadoh** [comment]
Alguna forma de hacerlos compatibles?

 

De: Gonzalo De Spirito ***@***.***> 
Enviado el: viernes, 2 de julio de 2021 18:08
Para: TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest ***@***.***>
CC: dsalgadoh ***@***.***>; Author ***@***.***>
Asunto: Re: [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest] Error crítico con plugins Google Listings & Ads (#72)

 

Sip, no son compatibles las versiones de guzzle que los plugins usan. Debes elegir entre uno u otro.

**Comment by gonzunigad** [comment]
Puedes descargar el código fuente del plugin, cambiar la versión de guzzle a la misma que tenga el otro plugin, correr `composer update`, y luego empacar el plugin con `TRAVIS_TAG=1.4.9 ./package.sh`
