### ISSUE TITLE
Falta un callback para receipt_page

### ISSUE THREAD

**Issue by nigelheap** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#85]
**Describe el bug**

Action no tiene un callback que causa un warning. 
add_action('woocommerce_receipt_'.$this->id, [$this, 'receipt_page']);

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WC_Gateway_Transbank_Webpay_Plus_REST' does not have a method 'receipt_page' in /var/www/selcap/wp-includes/class-wp-hook.php on line 292

**Para reproducir**

Accerder la pagina de pago cone errores activatado

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: [1.5.0]
- Woocommerce: [5.5.2]
- PHP: [7.3]

**Comment by gonzunigad** [comment]
Hola @nigelheap! Gracias por el reporte.  Yo estoy usando lo mismo. Versión 1.5.0, Wocommmerce 5.5.2 y PHP 7.3 y no veo ese problema. ¿Me podrías compartir un pantallazo? ¿El error te aparece en que momento?¿Oneclick o WebpayPlus?

**Comment by nigelheap** [comment]
Solo aparece en la pagina de pago, con warnings activado en PHP 

![Screen Shot 2021-07-27 at 8 09 17 am](https://user-images.githubusercontent.com/293999/127065663-0c1171e9-7396-4506-b788-30aed057dddd.png)

Viene de ese linea:
https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest/blob/master/plugin/webpay-rest.php#L138

**Comment by gonzunigad** [comment]
Creo que ya encontré el problema. Sacando nueva versión...
