### ISSUE TITLE
Error al pagar ambiente integracion "Will not follow more than 5 redirects"

### ISSUE THREAD

**Issue by redbytecl** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#90]
**Ocurrió un error al intentar conectar con WebPay Plus. Por favor intenta mas tarde.**

En el ambiente de integración el plugin Transbank Webpay REST me funcionaba bien con todas las transacciones hasta el día de hoy. El plugin estuvo 30 días de pruebas OK, pero hoy arrojo error. Al momento de comprar o de realizar diagnostico del plugin arroja error de conexión "Will not follow more than 5 redirects"

**Lo que he intentado para solucionar**

1. desactivar y activar plugin Transbank Webpay REST - no funcionó
2. Desinstalar y volver a instalar plugin Transbank Webpay REST - no funcionó
3. Instalar otro plugin de otro proveedor - FUNCIONÓ.

NOTA: NO SE HA REALIZADO NINGUN CAMBIO EN EL SITIO WEB QUE PUDIESE HABER PROVOCADO EL ERROR.

**Comment by Yoteman** [comment]
Hola, una consulta: ¿al instalar el plugin de otro proveedor, se aregló Webpay o dejaste funcionando el plugin del otro proveedor? ¿qué plugin era?

**Comment by redbytecl** [comment]
Se desactivó y desinstaló el plugin Transbank Webpay REST. Después se uso otro proveedor de plugin con pasarela de pago webpay y se corrigió el problema.

**Comment by ffiebig** [comment]
Que extraño que te haya pasado esto en integración, el único caso conocido al respecto ocurre con ciertos proveedores de servidores que son marcados como peligro de fraude por parte de proveedores de seguridad de Transbank, que bueno que ya lo solucionaste. 

Puedo preguntar que proveedor ? A ver si logramos hacerle sentido al error.

**Comment by ArkanHELLCL** [comment]
Tengo el mismo problema con una instalcion de woocomerce 8.2.1, php 8.1.11 y wp 6.3.2
