### ISSUE TITLE
Problema al autorizar el pago... no retorna a la tienda

### ISSUE THREAD

**Issue by rorromontenegro** [TransbankDevelopers/transbank-plugin-woocommerce-webpay-rest#93]
Estimados:
Junto con saludar y felicitar por el trabajo que han hecho. Quisiera contarles que tengo un problema, el cual paso a describir.
Instalé el plugin y seguí todos los pasos según el tutorial, hasta llegar a producción.

El problema ocurre cuando autorizo el pago de mi tarjeta, queda pegado y no vuelve a la tienda. Finalmente aparece un error 504. Después de eso, si actualizo la página, aparece la tienda con el reporte del pedido recibido, pero no ejecuta normalmente. El descuento del dinero de la tarjeta ocurre correctamente y el pedido queda en estado de Procesando.

**Describe el bug**

Una descripción conci
<img width="1742" alt="Captura de Pantalla 2021-11-29 a la(s) 13 51 18" src="https://user-images.githubusercontent.com/19996870/143909317-0c04b6b7-665f-4c8b-a939-53632dfce742.png">
s
<img width="1935" alt="Captura de Pantalla 2021-11-29 a la(s) 13 35 26" src="https://user-images.githubusercontent.com/19996870/143909249-aadfeb7a-c588-4740-b9f4-20670c975eb7.png">
a sobre el bug.

- Plugin:  Versión 1.5.3
- Woocommerce: Versión 5.9.0
- PHP: 7.1

**Comment by mastudillot** [comment]
Ese error puede ser por la configuración de tu servidor web. Si tienes otro problema no dudes en crear otra incidencia o hablarnos por Slack.
